dist: trusty
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_1a2cff5fdb56_key -iv $encrypted_1a2cff5fdb56_iv
  -in certificate.pem.enc -out scripts/signapk/certificate.pem -d
- chmod +x scripts/*.{sh,py}
- scripts/install-dependencies.sh
install: scripts/gettoolchains.sh
script: scripts/readytorock.sh
env:
  global:
  - VER="1.26.2-YDS"
  - STATUS="stable"
  - BUILD_TAG="v${VER}-${TRAVIS_BUILD_NUMBER}"
  matrix:
  - TO_BUILD="boxemup"
  - TO_BUILD="arm arm64"
  - TO_BUILD="x86 x86_64"
  - TO_BUILD="mips mips64"
  - TO_BUILD="mipseb"
deploy:
  provider: releases
  api_key:
    secure: oSU/NY1BofArTl24NtXgYdTSnyzm1a582pBKY6l//n5Bx0TCBhvkRnZNDUE6RyFLeXcIiiKZFF/qfBsRhRreLHV7vVT1I/GeTyfCtvlYPwsAgDJKOuVFjqpNJu5AzSn7Z4G+1AbVSaF3TzYCOCLkB8Jvx0axC5rdH7EDj7XQYH7xzvsecwC6zK9oHYdTdAS7i88VQd02B5fWSImoKNRtULsTwOD7orSL1Y3bkG3fjUgW0lccex9PjmJYJwzG9LXsgl2/rIt/aIMQU2dwZ3s8xsEmf5nMEkxHhjXxeCtxSRX3G+YO4/U7GinjZi2869D+dt7cRzNYGzfnKyLxDla8Sb82n9oiRsl9wIW7RtMEwl2Js8YGj7toBftwLX/UcWBiw1GoRBCFL/Pf2wwzTeA3pXgn3QNt2bcZC3ulGMZ64BEcAdmtscUZc7JtfwnTmxXhYQwES570BoMKmVgprT6QJJ/qim7Du+s6fTtJvwqBSU1YlPHPjGy3/EdJH4hKuKkN+O0ulPk1MPhf/BGLCi4YMepQvxxZ/AxvVPtJJrGWhQW7XGKThY9ZdwxhnZyJSQmmEAfc8ieWp9+9yyojQlMN+QEG9+5AAbAv5f5Fip/pZ3gwcqM4MSRFHwixxVv9iACEA6byYxpy20yWM231O1sW25Oq9pZoSgRSYCAnsd8rOc8=
  file: bbx/out/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: yashdsaraf/bb-bot
