dist: trusty
sudo: required
before_install:
  - openssl aes-256-cbc -K $encrypted_745e51b9b24e_key -iv $encrypted_745e51b9b24e_iv -in certificate.pem.enc -out scripts/signapk/certificate.pem -d
  - chmod +x scripts/*.{sh,py}
  - scripts/install-dependencies.sh
install:
  - if test "$TO_BUILD" != "boxemup"; then scripts/gettoolchains.sh; else pip install -q requests; fi
script: scripts/readytorock.sh
env:
  global:
    - VER="1.26.2-YDS"
    - STATUS="stable"
    - BUILD_TAG="v${VER}-${TRAVIS_BUILD_NUMBER}"
  matrix:
    - TO_BUILD="boxemup"
    - TO_BUILD="arm arm64"
    - TO_BUILD="x86 x86_64"
    - TO_BUILD="mips mips64"
    - TO_BUILD="mipseb"
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: btDNEDzrs05cuIHBPaycJ69YoGsU/j6LF+jnnKBFWd2feDEm1VRRsmQmOPkBixMSkneY2xwe1OuPcDccESpt/42pq5M3PeVuKR3AbInwAXaoxk+xTSMXzjE0zZ2MvRIie9aOnIhg/ujbWYk7rSSBQMzzYJ4MmuqksLfCzhsnV+qgLuJv3zarTbpc88jn8Us327bzCckOI+rBy/64+uHmKtZP0mSYw41RFoCkuSiUAWqD5oYZ1iTVSJz7NOQO/ragU/s9mIhvDZtBqJoQNONRZnsgkYhArI5XxULApueXGdWbCWxoh+SJur4Li7cxtJ39WHGrcS5uGmvNoj5+4SF/vyhkgJTNJZc1iP2qomNFp+vS+x3UkCIUWY7zWJb6WvUzAl30m6GcnBTuC+uq48kr+2OXNgo7ZP9d3A+iDn3ne7alNQ8/Rcw1aKK+/o6aZzE4kMKlv1wcWEwB4E2gBHLG5KcT85EdTcai6x8QniV4ru/bjcrCjucV7tKcbAEetdvba2uY/n8ceyHOuJlE2u/psNIwjsXtqZcyt4yZW/XDqtVZB0aYe/iupc4YC7VapA4nNr8xUrh8BZLacA5F1r52YU2m/itmcGusw6oEI2mIgMPjWqGpejpda27Z0bNeTzyI7S3oa95Q0wtcqifMXKfMIZ3EgHqtKlAz4669Sd/FrfY=
  file: bbx/out/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: yashdsaraf/bb-bot
    branch: testing
