dist: trusty
sudo: required
language: python
python: "3.5"
before_install:
  - openssl aes-256-cbc -K $encrypted_1a2cff5fdb56_key -iv $encrypted_1a2cff5fdb56_iv -in certificate.pem.enc -out scripts/signapk/certificate.pem -d
  - chmod +x scripts/*.{sh,py}
  - scripts/install-dependencies.sh
install: scripts/gettoolchains.sh
script: scripts/readytorock.sh
env:
  global:
    - VER="1.26.2-YDS"
    - STATUS="stable"
    - BUILD_TAG="v${VER}-${TRAVIS_BUILD_NUMBER}"
  matrix:
    - TO_BUILD="boxemup"
    - TO_BUILD="arm arm64"
    - TO_BUILD="x86 x86_64"
    - TO_BUILD="mips mips64"
    - TO_BUILD="mipseb"
after_success: git -c user.email="travis@travis-ci.org" -c user.name="Travis" fetch origin
deploy:
  provider: releases
  prerelease: true
  api_key: $TOKEN
  file: bbx/out/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
    repo: yashdsaraf/bb-bot
    all_branches: true