dist: trusty
sudo: required
env:
  - VER="1.26.2-YDS"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq p7zip-full realpath
  - chmod +x scripts/*
install: true
script: "./scripts/readytorock.sh"
after_success:
  - "./scripts/settags.sh"
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: kl5QcSTO7wGygBGmCwJZNsfBw7SgTxjREKGKB8xdaVUroTgWfcRKcD7U75CUbTdj47IO8eG8vbgc/MN21I1X692nhduxAkx1961dBkDwE4m6q5133EPNXrxI5MNpCO5vur+XQHzWMCkAC58ffBTMuS57ygeP7NAXA5Td5ZGj3mXrfYDWmnH6wDb68iAwUjT0J1sMUMpT3nQ56Fz6FMThTz1ArcojK5ncwvxmMEOWR8PplmsDPf4KGJxcrad5MjjMujjx6JcZ3tVNfNJwy9w1EyTgoccaIQ+fj6Efh1g2uLLn0n3UUOANLTsYcb1vWf86ucJBtGIvwQuj4NyyFqdsTuEzCAUKEgxcj1R0sCWBeAl6/UvM6IvSxhQl5YJH+XQg7jUKcMLxy703tuah4qNgUs1ENJkQuk7XhZltsfL2Fcj7q/BRBlfzTs7qYaPtxDBKVdVmBlDeXQfF8OXoweaKEgJhl3lcQUY0FaBI4vJqE+uVJvVem9m4iBjdOi8IGvfi1NKJFAF4nmpgFW7GbJT2F0bsdN/gfj2CrvQpPF/N8JN/GqaE3miHMk0j3iTjy+q2duUI2PtuLfXZJonTR0bxed+ZMSkRMEaJ+FN3SotzxNsV8VgqIhEjQo+QppCkvXt1JdgUPT+uQwm8yVx2WVQF4jH5Rc6PAYUo8CAmPEj5Tz4=
  file:
    - "./bbx/out/*/*.zip"
    - "./bbx/out/*/Tars/*.tar.gz"
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: testing
    repo: yashdsaraf/bb-bot
